export const nowTodo = [
  'Vakkaru Island Resort',
  'Vakkaru_Maldives',
  'Vakkaru Maldives',
  'The Vakkaru Over Water Residence',
  'Deluxe Beach Pool Suite of Vakkaru Maldives',
  'Beach Villas of Vakkaru Maldives',

]

export const nowTodo1 = [
//   'Amilla Maldives Resort and Residences',
//   'Amilla Maldives Resort & Residences',
//   'amilla_fushi_maldives_resort',
//   'Amilla Maldives',
//   'Eid at Amilla Residences',
//   'Festive at Amilla',
//   'Amilla Allure',
//   'Eid Al Adha at Amilla',
//   'Amilla Maldives ',
//   'Amilla Fushi',
//   'Amilla Fushi Resort',
//   'Amilla Estate',
//   'amilla estate',
//   'Royal Island Resort',
//   'Royal Island Resort & Spa',
//   'Villa Nautica',
//   'Villa Nautica in Lankanfinolhu Island, Maldives',
//   'Villa Nautica Paradise Island Resort',
//   'Villa Nautica, Maldives',
  'Kandima Maldives',
  'kandima_maldives',
'Kandima Resort',
  'kandima_resort',
  'candema_resort',
  'Candema Resort',
  'candima_resort',
  'Candima Resort',
  'kandima Maldives',
  'kandima maldives',
  'kandima',
  'kandima_resort_pool_center',
  'kandima_resort_pool_beach_club',
  'kandima_resort_transportation',
  'kandima_resort_get_around',
  'kandima_resort_room_categories',
  'kandima_lifestyle_hotel',
  'kandima_lux_hotel',
  'kandima beach',
  'Kandima',




]